"""Generate runnable Foundry tests from a Finding's structured PoC.

Two roles:
  * ``scaffold_poc()`` — turn a ``FoundryPoc`` into a ``.t.sol`` file
    that ``forge test`` can pick up.
  * ``execute_poc()`` — run ``forge test`` against the generated file
    and classify the result: reproduced / unconfirmed / compile-error /
    not-applicable.

A finding whose PoC's test *fails* on the buggy code is "reproduced" —
this is the AFL-crash-file analog: anyone can clone the repo, run
``forge test --match-contract <FindingX>Test`` and watch the demonstration.
"""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

from harness.schema import Finding, FoundryPoc

REPO_ROOT = Path(__file__).resolve().parent.parent

POC_FILE_TEMPLATE = """\
// SPDX-License-Identifier: MIT
// AUTO-GENERATED by web3Sentinel — see audits/<run>/poc/ for context.
// DO NOT EDIT IN PLACE: regeneration overwrites this file.
pragma solidity ^0.8.20;

import "forge-std/Test.sol";
{imports}

/// @notice Reproducer for finding: {finding_title}
/// @dev Severity: {severity} | Discovered by: {discovered_by}
contract {contract_name} is Test {{
    // -- setUp --------------------------------------------------------
    function setUp() public {{
{setup_body}
    }}

    // -- exploit ------------------------------------------------------
    function {test_name}() public {{
{exploit_body}

        // -- assertion ------------------------------------------------
{assertion_body}
    }}
}}
"""


def _sanitize_contract_name(s: str) -> str:
    """Title -> CamelCase Solidity identifier. Idempotent on already-clean input."""
    s = re.sub(r"[^A-Za-z0-9 ]+", " ", s)
    parts = [p for p in s.split() if p]
    name = "".join(p[:1].upper() + p[1:] for p in parts)
    if not name:
        name = "Finding"
    if not name[0].isalpha():
        name = "F" + name
    return name[:60] + "Test"


def _normalize_test_name(name: str) -> str:
    """test_X is required by forge; sanitize anything else into shape."""
    name = re.sub(r"[^A-Za-z0-9_]", "_", name).strip("_") or "test_reproduces"
    if not name.startswith("test_"):
        name = "test_" + name
    return name[:80]


def _indent(body: str, levels: int = 2) -> str:
    """Indent each non-blank line by `levels` * 4 spaces."""
    pad = " " * (4 * levels)
    return "\n".join((pad + line if line.strip() else line) for line in body.splitlines())


@dataclass
class ScaffoldResult:
    test_path: Path
    contract_name: str
    test_name: str


def scaffold_poc(
    finding: Finding,
    *,
    out_dir: Path,
    finding_index: int = 0,
) -> ScaffoldResult | None:
    """Write the PoC to ``out_dir/<contract>.t.sol``. Returns None if the
    finding has no structured foundry_poc.
    """
    if not finding.foundry_poc:
        return None

    out_dir.mkdir(parents=True, exist_ok=True)

    poc: FoundryPoc = finding.foundry_poc
    contract_name = _sanitize_contract_name(f"{finding.title}-{finding_index}")
    test_name = _normalize_test_name(poc.test_name)
    imports_block = "\n".join(f'import "{imp}";' for imp in poc.imports) if poc.imports else ""

    content = POC_FILE_TEMPLATE.format(
        finding_title=finding.title.replace('"', "'"),
        severity=finding.severity,
        discovered_by=finding.discovered_by,
        contract_name=contract_name,
        test_name=test_name,
        setup_body=_indent(poc.setup, levels=2),
        exploit_body=_indent(poc.exploit, levels=2),
        assertion_body=_indent(poc.assertion, levels=2),
        imports=imports_block,
    )

    out_path = out_dir / f"{contract_name}.t.sol"
    out_path.write_text(content)
    return ScaffoldResult(out_path, contract_name, test_name)


# ---------------------------------------------------------------------------
# Executor
# ---------------------------------------------------------------------------


@dataclass
class ExecutionResult:
    status: str  # "reproduced" | "unconfirmed" | "compile-error" | "not-applicable"
    test_path: Path
    stdout: str
    stderr: str
    returncode: int


def _forge_bin() -> str | None:
    candidates = [
        Path(sys.prefix) / "bin" / "forge",
        Path.home() / ".foundry" / "bin" / "forge",
    ]
    for c in candidates:
        if c.is_file() and os.access(c, os.X_OK):
            return str(c)
    return shutil.which("forge")


def execute_poc(
    test_path: Path,
    contract_name: str,
    test_name: str,
    *,
    project_root: Path,
    timeout_seconds: int = 180,
) -> ExecutionResult:
    """Run `forge test` against the generated PoC.

    Semantics:
      * The PoC's `assertion` body is the bug demonstration. If the
        assertion is something like ``assertGt(attacker.balance, ...)``
        and it PASSES, the bug is "reproduced".
      * If forge can't compile (missing imports, wrong types), we tag
        ``compile-error`` — the auditor likely produced a sketch rather
        than a runnable PoC.
      * If forge runs but the assertion fails, the bug is "unconfirmed"
        — the proposed exploit didn't manifest as described.
    """
    forge = _forge_bin()
    if not forge:
        return ExecutionResult(
            status="not-applicable",
            test_path=test_path,
            stdout="",
            stderr="forge binary not on PATH",
            returncode=-1,
        )

    if not (project_root / "foundry.toml").exists():
        return ExecutionResult(
            status="not-applicable",
            test_path=test_path,
            stdout="",
            stderr=f"no foundry.toml at {project_root} — PoCs require a Foundry-shaped target",
            returncode=-1,
        )

    env = os.environ.copy()
    env["PATH"] = os.pathsep.join(
        [
            str(Path(sys.prefix) / "bin"),
            str(Path.home() / ".foundry" / "bin"),
            env.get("PATH", ""),
        ]
    )

    cmd = [
        forge,
        "test",
        "--match-contract",
        contract_name,
        "--match-test",
        test_name,
        "-vv",
    ]

    try:
        proc = subprocess.run(
            cmd,
            cwd=str(project_root),
            capture_output=True,
            text=True,
            timeout=timeout_seconds,
            env=env,
            check=False,
        )
    except subprocess.TimeoutExpired:
        return ExecutionResult(
            status="unconfirmed",
            test_path=test_path,
            stdout="",
            stderr=f"forge test timed out after {timeout_seconds}s",
            returncode=-1,
        )

    out = proc.stdout
    err = proc.stderr
    rc = proc.returncode

    # Heuristic classification of forge output.
    combined = (out + "\n" + err).lower()
    if "compiler run failed" in combined or "error (" in combined and "compiler" in combined:
        status = "compile-error"
    elif rc == 0 and "passed" in combined and contract_name.lower() in combined:
        status = "reproduced"
    elif "[fail]" in combined or "[fail. reason" in combined:
        status = "unconfirmed"
    else:
        # Anything else (forge didn't find the test, etc.) we treat as unconfirmed.
        status = "unconfirmed"

    return ExecutionResult(status, test_path, out, err, rc)


# ---------------------------------------------------------------------------
# Orchestrator (called from audit_runner finalize)
# ---------------------------------------------------------------------------


def attempt_all(
    findings: list[Finding],
    *,
    run_dir: Path,
    project_root: Path,
    progress: "Callable[[int, int, Finding, str], None] | None" = None,
) -> list[Finding]:
    """For each finding with a structured foundry_poc, scaffold + execute.

    Mutates the findings in place (sets `poc_status` and `poc_artifacts`)
    and returns the same list for chainability.

    ``progress(idx, total, finding, phase)`` is called for status changes:
    phase ∈ {"scaffolding", "running", "done:<status>", "skipped"}.
    """
    poc_dir = run_dir / "poc"
    total = len(findings)
    for i, f in enumerate(findings):
        if not f.foundry_poc:
            f.poc_status = "not-applicable"
            if progress:
                progress(i, total, f, "skipped")
            continue
        if progress:
            progress(i, total, f, "scaffolding")
        scaffold = scaffold_poc(f, out_dir=poc_dir, finding_index=i)
        if not scaffold:
            f.poc_status = "not-applicable"
            if progress:
                progress(i, total, f, "skipped")
            continue

        if progress:
            progress(i, total, f, "running")
        exec_result = execute_poc(
            scaffold.test_path,
            scaffold.contract_name,
            scaffold.test_name,
            project_root=project_root,
        )
        f.poc_status = exec_result.status
        stdout_log = poc_dir / f"{scaffold.contract_name}.stdout.log"
        stderr_log = poc_dir / f"{scaffold.contract_name}.stderr.log"
        stdout_log.write_text(exec_result.stdout)
        stderr_log.write_text(exec_result.stderr)
        f.poc_artifacts = {
            "test_path": str(scaffold.test_path.relative_to(REPO_ROOT))
            if scaffold.test_path.is_relative_to(REPO_ROOT)
            else str(scaffold.test_path),
            "stdout_log": str(stdout_log.relative_to(REPO_ROOT))
            if stdout_log.is_relative_to(REPO_ROOT)
            else str(stdout_log),
            "stderr_log": str(stderr_log.relative_to(REPO_ROOT))
            if stderr_log.is_relative_to(REPO_ROOT)
            else str(stderr_log),
        }
        if progress:
            progress(i, total, f, f"done:{exec_result.status}")
    return findings
